### ISSUE TITLE
delegate method for ending pan

### ISSUE THREAD

**Issue by RyuX51** [alankarmisra/SwiftSignatureView#24]
Shouldn't `swiftSignatureViewDidPanInside` be rather called when the pan gesture ended? If it's meaned this way - you could you add a `swiftSignatureViewDidFinishPanInside` when the `pan.state == .ended`.

**Comment by alankarmisra** [comment]
I think this was contributed code (I can't imagine a use-case for this but I won't argue). However, you're right in that the event callback provides no valuable information about the pan state itself. Consequently, rather than deciding on when to trigger an event (start/change/ended), I've chosen to trigger it whenever a pan gesture is recognized and I send along the pan gesture object itself so the listener can decide what to do with it. Unfortunately this changes the public interface a little bit but hopefully nobody will complain :) Thank you for your valuable contribution!
