### ISSUE TITLE
delegates are not working

### ISSUE THREAD

**Issue by ajurav1** [alankarmisra/SwiftSignatureView#40]
• After new update delegates are not working for iOS 13
• Also even after calling clear() signature image won't be nil, So how to check sign is blank?

All functionality of my app broken due to new instance for iOS13 in new PencilKitSignatureView.
Is there any workaround to use LegacySwiftSignatureView, might that solve the above 2 issue

**Comment by alankarmisra** [comment]
Sorry you had trouble with the new version. Will check and fix on the weekend. In the meantime, you can open the pod class SwiftSignatureView.swift, find the function _createSignatureView_  and replace
```swift
if #available(iOS 13.0, *) {
     instance = PencilKitSignatureView(frame:bounds);
  } else {
     instance = LegacySwiftSignatureView(frame:bounds);
 }
```

with just this:
```swift
instance = LegacySwiftSignatureView(frame:bounds);` 
```

**Comment by alankarmisra** [comment]
I just realized that this won't fix your issues with delegates or with clear signature. I'll definitely fix it this weekend. In the meantime you might want to try using LegacySwiftSignatureView directly on your UIView, instead of SwiftSignatureView since that supports the same interface and also sends out delegate events. Let me know if you have trouble with this.

**Comment by ajurav1** [comment]
Yes, that won't fix the issue.
However, I have downcast to `pod 'SwiftSignatureView', '2.2.3' ` & Its working now.
Will look for an update. Thanks

**Comment by alankarmisra** [comment]
In 3.2.0, we've changed the _SwiftSignatureViewDelegate_ interface to pass on all gestures through the _swiftSignatureViewDidDrawGesture_ delegate method. 

Furthermore there is an _isEmpty_ method now that will tell you if the canvas is clear (instead of using a nil check). 

Would these changes resolve your issue? If not, let me know. Or we can close this issue!

**Comment by alankarmisra** [comment]
Closing this, since I think it resolves your issues. If you still have trouble, feel free to reopen this.
