### ISSUE TITLE
Swift 2.3 / 3 Support

### ISSUE THREAD

**Issue by twiedow** [alankarmisra/SwiftSignatureView#9]
Hi,

I just like to know how your plans are about releasing a Swift 2.3 / Swift 3 compatible version?

Thanks,

Tobi

**Comment by alankarmisra** [comment]
I could create one by this weekend? But I think I'll have to put it in a different branch so I don't break existing installs still running on Swift 2.

**Comment by twiedow** [comment]
Do you have a plan when to switch to Swift 2.3 or 3? Since Xcode 8 will force the user to switch...

**Comment by alankarmisra** [comment]
Sure. Is XCode 8 out of beta yet though? I'm not really keeping track due to some Android commitments but if it's out of beta, I'll definitely move the repo to XCode 8 + Swift 3.

**Comment by twiedow** [comment]
Yesterday the GM version was released.

**Comment by alankarmisra** [comment]
Yes, I just saw that! In that case, yes, I think it's time we adopted Swift 3 + XCode 8. I'll try and get it done by the weekend. Thanks for the ping! 👍

**Comment by twiedow** [comment]
It would be great if you could also either create a branch or release before the Swift 3 release which uses Swift 2.3. Then people could choose between a version using Swift 2.3 or 3. You could make further development on the Swift 3 version.

**Comment by alankarmisra** [comment]
Sounds like a plan. Will do. Gimme until the weekend to update the lib.

**Comment by twiedow** [comment]
Thanks a lot!

**Comment by alankarmisra** [comment]
So it turns out that the class file will work without changes in Swift 2.3. I've upload a new version with an XCode 8 compatible example to github but I'm unable to update the Cocoapod repository due to a bug in the Cocoapod system that fails to create a project with XCode 8. For now, I suggest you continue using 1.0.2 and let XCode "convert" the code to 2.3 - all it will do is change the build settings for that framework to use "legacy" Swift code which is 2.3, but other than that it will just work. I'll update the Cocoapod repo as soon as they fix their issue with XCode 8. I'll keep this issue open for now.

**Comment by alankarmisra** [comment]
So it turns out that the class file will work without changes in Swift 2.3. I've upload a new version with an XCode 8 compatible example to github but I'm unable to update the Cocoapod repository due to a bug in the Cocoapod system that fails to create a project with XCode 8. For now, I suggest you continue using 1.0.2 and let XCode "convert" the code to 2.3 - all it will do is change the build settings for that framework to use "legacy" Swift code which is 2.3, but other than that it will just work. I'll update the Cocoapod repo as soon as they fix their issue with XCode 8. I'll keep this issue open for now.

**Comment by twiedow** [comment]
Did you try to update the pod with the new cocopoads? There is an update with better Xcode 8 support.

**Comment by alankarmisra** [comment]
Yes, but it still won't work. I'm looking into it.

**Comment by alankarmisra** [comment]
Ok it's been resolved. Could you ensure it works for you? I'll close the issue once you confirm that it works for you.

**Comment by twiedow** [comment]
Thanks a lot! I just could download the release via Cocoapods. Would be great if you could release a Swift 3 version as well. We plan to migrate our project to Swift 3 in the next 2 or 3 weeks, so we would be happy to have a release then.

**Comment by alankarmisra** [comment]
Yes no worries. I'll probably release it by next week. Will probably create a different branch for it (which you can still access from Cocoapods by specifying the branch I think).
